### ISSUE TITLE
Couldn't find ionic.config.json file. Are you in an Ionic project? - Error

### ISSUE THREAD

**Issue by vipinsainitech** [iursevla/ionic2-PreDB#3]
@iursevla @RuiGarciaAlves 
Getting `Couldn't find ionic.config.json file. Are you in an Ionic project?` error after run this project first time.

![screen shot 2017-06-13 at 8 55 24 pm](https://user-images.githubusercontent.com/16730481/27090984-6c8f0bfc-507c-11e7-8a57-31d0d5ef1cc4.png)

Please help me to solve this issue.
Thanks.

**Comment by iursevla** [comment]
Hi,

You have to change your directory first. 
`cd prePopulated` and then

Inside the project folder run: `npm install` 
Next:` ionic build android`
After that: `ionic run android`

@vipinsaini0  
Did it solve your issue?

**Comment by vipinsainitech** [comment]
@iursevla @RuiGarciaAlves Now, getting this error after run on device from below command.
`$ ionic run android --device`

ANDROID_HOME=/Users/AbcUser/Library/Android/sdk

JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home

**Error: Cannot read property 'length' of undefined**

**Comment by iursevla** [comment]
@vipinsaini0 
Please post the full error message (can be in an image)
Then run `ionic info` on your project and post the results here too.

**Comment by vipinsainitech** [comment]
@iursevla @RuiGarciaAlves 
- Error below in an image

------------------------------------------------------
![screen shot 2017-06-14 at 8 02 39 am](https://user-images.githubusercontent.com/16730481/27113237-57854570-50d9-11e7-92b4-92e7dd905ce5.png)


- `ionic info` below in an image

----------------------------------------------------------
![screen shot 2017-06-14 at 8 14 28 am](https://user-images.githubusercontent.com/16730481/27113367-024a8cf4-50da-11e7-857f-55b978b361f6.png)

**Comment by iursevla** [comment]
Are you trying to open in a device or in an emulator like Genymotion?

Try updating your ionic CLI version because it is outdated.

Then try `ionic cordova run android `
