### ISSUE TITLE
ionic build android failing

### ISSUE THREAD

**Issue by zeexan-dev** [iursevla/ionic2-PreDB#4]
Following is the screenshot attached.
![screenshot_2](https://user-images.githubusercontent.com/6541601/27266046-de2205c4-54b6-11e7-84f5-47165540377f.png)

**Comment by iursevla** [comment]
Hi,

Did you solve the problem?

**Comment by zeexan-dev** [comment]
Yeah I did. I updated both Ionic and Cordova. Removed platform, added plugins again and then added android platform. Build was successful then

**Comment by iursevla** [comment]
Did the pre-populated work as expected? 
Thanks for replying.

**Comment by zeexan-dev** [comment]
Yup. it worked
