### ISSUE TITLE
Test/support with Ionic 3?

### ISSUE THREAD

**Issue by brody2consult** [iursevla/ionic2-PreDB#6]
ref: <https://github.com/litehelpers/cordova-sqlite-ext/issues/66>

**Comment by iursevla** [comment]
@brodybits see my comment on the topic [litehelpers/cordova-sqlite-ext/issues/66](https://github.com/litehelpers/cordova-sqlite-ext/issues/54#issuecomment-340268169)

**Comment by iursevla** [comment]
@brodybits will close 
See https://github.com/iursevla/ionic3-PreDB for a version working with ionic3. Probably will create a version for Ionic 4 as soon as possible.

**Comment by brody2consult** [comment]
Thanks again!
